steps:
  - name: gradle:6.6.1-jdk11
    entrypoint: gradle
    args: ["test"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hello-spring", "."]
images: ["gcr.io/$PROJECT_ID/hello-spring"]
